name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          ssh-keyscan -H 18.142.53.167 >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ssh_key -o StrictHostKeyChecking=no root@18.142.53.167 << 'EOF'
            set -e
            cd /root/bookmyshowtype/
            git pull origin main
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:$PATH
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart fe-sever || pm2 start fe-sever
            pm2 restart http-sever || pm2 start http-sever
            pm2 restart ws-sever || pm2 start ws-sever
            echo "Deployment completed successfully!"
          EOF